<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="TCP_IP" Id="{b3a78b8f-7402-46f3-942d-2e14f4eca26b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TCP_IP
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TCP_IP">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>