<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="Decoder" Id="{1cfc5b98-9cc8-438c-ae60-709acd6a425e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Decoder
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Decoder">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>